// Phase-9 safety boundary: backups are local downloads only; credentials, external iframe data and browser secrets are excluded.
import { initializeVocabularyDb } from "@/lib/vocabulary-db";
export const BACKUP_VERSION = 1;
const DATA_STORES = ["words","settings","exam-sessions","exam-history","word-performance","revision-queue","performance-events","gamification-state","gamification-events","reward-transactions","daily-goals","achievements","shop-ownership","word-tools","personal-notes","custom-lists","custom-list-items","word-of-day","tool-history","learning-targets","planner-state"];
export type BackupFile = { app: "Vocabulary Master"; backupVersion: number; createdAt: string; schemaVersion: number; data: Record<string, unknown[]> };
export type BackupPreview = { vocabulary: number; exams: number; notes: number; lists: number; performance: number; createdAt: string; backupVersion: number };
const read = <T,>(request: IDBRequest<T>) => new Promise<T>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error??new Error("Local data could not be read."));});
const tx=async<T>(stores:string|string[],mode:IDBTransactionMode,run:(t:IDBTransaction)=>Promise<T>)=>{const db=await initializeVocabularyDb();try{return await run(db.transaction(stores,mode));}finally{db.close();}};
export async function createBackup():Promise<BackupFile>{const db=await initializeVocabularyDb();try{const present=DATA_STORES.filter(store=>db.objectStoreNames.contains(store));const transaction=db.transaction(present,"readonly");const data:Record<string,unknown[]>={};for(const name of present)data[name]=await read(transaction.objectStore(name).getAll());return {app:"Vocabulary Master",backupVersion:BACKUP_VERSION,createdAt:new Date().toISOString(),schemaVersion:db.version,data};}finally{db.close();}}
export function validateBackup(value:unknown):{backup:BackupFile;preview:BackupPreview}{if(!value||typeof value!=="object")throw new Error("This is not a valid Vocabulary Master backup.");const backup=value as Partial<BackupFile>;if(backup.app!=="Vocabulary Master"||backup.backupVersion!==BACKUP_VERSION||!backup.data||typeof backup.data!=="object")throw new Error("Backup version is incompatible or incomplete.");for(const [store,records]of Object.entries(backup.data))if(!DATA_STORES.includes(store)||!Array.isArray(records))throw new Error("Backup contains an invalid data section.");const data=backup.data as Record<string,unknown[]>;return {backup:backup as BackupFile,preview:{vocabulary:data.words?.length??0,exams:data["exam-history"]?.length??0,notes:data["personal-notes"]?.length??0,lists:data["custom-lists"]?.length??0,performance:data["word-performance"]?.length??0,createdAt:backup.createdAt??"",backupVersion:backup.backupVersion}};}
export function downloadBackup(backup:BackupFile,kind:"FullBackup"|"Vocabulary"="FullBackup"){const payload=kind==="Vocabulary"?{app:"Vocabulary Master",backupVersion:BACKUP_VERSION,createdAt:backup.createdAt,data:{words:backup.data.words??[]}}:backup;const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`VocabularyMaster_${kind}_${backup.createdAt.slice(0,10)}.${kind==="FullBackup"?"vmb":"json"}`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
export async function parseBackupFile(file:File){const text=await file.text();try{return validateBackup(JSON.parse(text));}catch(error){throw error instanceof Error?error:new Error("Backup file could not be read.");}}
export async function createSafetySnapshot(backup:BackupFile){await tx("safety-backups","readwrite",async(transaction)=>{transaction.objectStore("safety-backups").put({snapshotId:`safety-${Date.now()}`,createdAt:new Date().toISOString(),backup});});}
export async function restoreBackup(backup:BackupFile){await createSafetySnapshot(await createBackup());const db=await initializeVocabularyDb();try{const names=Object.keys(backup.data).filter(name=>db.objectStoreNames.contains(name));const transaction=db.transaction(names,"readwrite");for(const name of names){const store=transaction.objectStore(name);store.clear();for(const item of backup.data[name])store.put(item);}await new Promise<void>((resolve,reject)=>{transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error??new Error("Restore could not be completed safely."));});}finally{db.close();}}
export async function dataHealth(){const db=await initializeVocabularyDb();try{const names=DATA_STORES.filter(name=>db.objectStoreNames.contains(name));const transaction=db.transaction(names,"readonly");const count=async(name:string)=>(await read(transaction.objectStore(name).count())) as number;const [words,performance,notes,lists,listItems]=await Promise.all([count("words"),count("word-performance"),count("personal-notes"),count("custom-lists"),count("custom-list-items")]);const bytes=JSON.stringify(await createBackup()).length;return {status:"Healthy",words,performance,notes,lists,listItems,estimatedBytes:bytes,checkedAt:new Date().toISOString()};}finally{db.close();}}
