// Phase-4 persistence: active sessions and submitted history are isolated from vocabulary records in the same versioned IndexedDB database.
import type { VocabularyWord } from "@/data/vocabulary";
import type { ExamHistoryRecord, ExamSession } from "@/lib/exam-engine";
import { EXAM_HISTORY_STORE, EXAM_SESSIONS_STORE, initializeVocabularyDb } from "@/lib/vocabulary-db";

async function transaction<T>(stores: string | string[], mode: IDBTransactionMode, action: (tx: IDBTransaction) => Promise<T>): Promise<T> { const db = await initializeVocabularyDb(); try { return await action(db.transaction(stores, mode)); } finally { db.close(); } }

export async function getExamCandidates(limit = 420, source = "all"): Promise<VocabularyWord[]> { return transaction("words", "readonly", async (tx) => new Promise<VocabularyWord[]>((resolve, reject) => { const store = tx.objectStore("words"); const index: IDBObjectStore | IDBIndex = source === "all" ? store.index("word") : store.index("firstLetter"); const request = index.openCursor(source === "all" ? undefined : IDBKeyRange.only(source)); const records: VocabularyWord[] = []; request.onerror = () => reject(request.error ?? new Error("Could not prepare vocabulary for the exam.")); request.onsuccess = () => { const cursor = request.result; if (!cursor || records.length >= limit) return resolve(records); records.push(cursor.value as VocabularyWord); cursor.continue(); }; })); }
export async function saveActiveExam(session: ExamSession): Promise<void> { await transaction(EXAM_SESSIONS_STORE, "readwrite", async (tx) => new Promise<void>((resolve, reject) => { tx.objectStore(EXAM_SESSIONS_STORE).put(session); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error ?? new Error("Could not save active exam.")); })); }
export async function getActiveExam(): Promise<ExamSession | null> { return transaction(EXAM_SESSIONS_STORE, "readonly", async (tx) => new Promise<ExamSession | null>((resolve, reject) => { const request = tx.objectStore(EXAM_SESSIONS_STORE).openCursor(); request.onerror = () => reject(request.error ?? new Error("Could not restore active exam.")); request.onsuccess = () => resolve((request.result?.value as ExamSession | undefined) ?? null); })); }
export async function discardActiveExam(examId: string): Promise<void> { await transaction(EXAM_SESSIONS_STORE, "readwrite", async (tx) => new Promise<void>((resolve, reject) => { tx.objectStore(EXAM_SESSIONS_STORE).delete(examId); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error ?? new Error("Could not discard active exam.")); })); }
export async function finalizeExam(record: ExamHistoryRecord): Promise<void> { await transaction([EXAM_SESSIONS_STORE, EXAM_HISTORY_STORE], "readwrite", async (tx) => new Promise<void>((resolve, reject) => { tx.objectStore(EXAM_HISTORY_STORE).put(record); tx.objectStore(EXAM_SESSIONS_STORE).delete(record.examId); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error ?? new Error("Could not save exam result.")); })); }
export async function getExamHistory(): Promise<ExamHistoryRecord[]> { return transaction(EXAM_HISTORY_STORE, "readonly", async (tx) => new Promise<ExamHistoryRecord[]>((resolve, reject) => { const request = tx.objectStore(EXAM_HISTORY_STORE).index("completedAt").openCursor(null, "prev"); const records: ExamHistoryRecord[] = []; request.onerror = () => reject(request.error ?? new Error("Could not read exam history.")); request.onsuccess = () => { const cursor = request.result; if (!cursor) return resolve(records); records.push(cursor.value as ExamHistoryRecord); cursor.continue(); }; })); }
