// Phase-5 persistence: compact performance records reference vocabulary IDs and consume submitted exam events exactly once.
import type { VocabularyWord } from "@/data/vocabulary";
import { getExamHistory } from "@/lib/exam-db";
import { calculatePerformance, emptyPerformance, performanceFromExam, priorityFor, revisionReason, type RevisionItem, type WordPerformance } from "@/lib/performance-engine";
import { initializeVocabularyDb } from "@/lib/vocabulary-db";

const PERFORMANCE = "word-performance"; const REVISION = "revision-queue"; const EVENTS = "performance-events"; const WORDS = "words";
async function transaction<T>(stores: string | string[], mode: IDBTransactionMode, action: (tx: IDBTransaction) => Promise<T>): Promise<T> { const db = await initializeVocabularyDb(); try { return await action(db.transaction(stores, mode)); } finally { db.close(); } }
function requestValue<T>(request: IDBRequest<T>) { return new Promise<T>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("Database request failed.")); }); }
export async function migrateExamPerformance() { const history = await getExamHistory(); for (const record of history) { for (const event of performanceFromExam(record)) await recordPerformanceEvent(event); } }
export async function recordPerformanceEvent(event: { eventId: string; vocabularyId: string; correct: boolean; kind: Parameters<typeof calculatePerformance>[2]; at: string }) { return transaction([PERFORMANCE, REVISION, EVENTS], "readwrite", async (tx) => { const events = tx.objectStore(EVENTS); if (await requestValue(events.get(event.eventId))) return false; const performanceStore = tx.objectStore(PERFORMANCE); const previous = (await requestValue(performanceStore.get(event.vocabularyId)) as WordPerformance | undefined) ?? emptyPerformance(event.vocabularyId); const next = calculatePerformance(previous, event.correct, event.kind, event.at); performanceStore.put(next); const priority = priorityFor(next); const revision = tx.objectStore(REVISION); if (next.wrong > 0 && priority > 0) revision.put({ vocabularyId: next.vocabularyId, priority, reason: revisionReason(next), scheduledAt: event.at, nextReviewAt: next.nextReviewAt } satisfies RevisionItem); else revision.delete(next.vocabularyId); events.put({ eventId: event.eventId, at: event.at }); return true; }); }
export async function getPerformance(vocabularyId: string): Promise<WordPerformance> { return transaction(PERFORMANCE, "readonly", async (tx) => (await requestValue(tx.objectStore(PERFORMANCE).get(vocabularyId)) as WordPerformance | undefined) ?? emptyPerformance(vocabularyId)); }
export async function getPerformanceSummary() { return transaction(PERFORMANCE, "readonly", async (tx) => { const values: WordPerformance[] = await requestValue(tx.objectStore(PERFORMANCE).getAll()); const attempted = values.filter((value) => value.attempts > 0); const overall = attempted.length ? Math.round(attempted.reduce((sum, value) => sum + value.mastery, 0) / attempted.length) : 0; const weak = attempted.filter((value) => value.mastery <= 40).length; const strong = attempted.filter((value) => value.mastery >= 61 && value.mastery < 96).length; const mastered = attempted.filter((value) => value.currentState === "mastered").length; return { overall, tracked: attempted.length, weak, strong, mastered }; }); }
export async function getRevisionItems(limit = 20) { return transaction([REVISION, WORDS], "readonly", async (tx) => { const queue = await requestValue(tx.objectStore(REVISION).getAll()) as RevisionItem[]; const words = tx.objectStore(WORDS); const rows: Array<{ item: RevisionItem; word: VocabularyWord }> = []; for (const item of queue.sort((a, b) => b.priority - a.priority).slice(0, limit)) { const word = await requestValue(words.get(item.vocabularyId)) as VocabularyWord | undefined; if (word) rows.push({ item, word }); } return rows; }); }
export async function getMistakes() { return transaction([PERFORMANCE, WORDS], "readonly", async (tx) => { const performances = await requestValue(tx.objectStore(PERFORMANCE).getAll()) as WordPerformance[]; const words = tx.objectStore(WORDS); const rows: Array<{ performance: WordPerformance; word: VocabularyWord }> = []; for (const performance of performances.filter((item) => item.wrong > 0)) { const word = await requestValue(words.get(performance.vocabularyId)) as VocabularyWord | undefined; if (word) rows.push({ performance, word }); } return rows.sort((a, b) => priorityFor(b.performance) - priorityFor(a.performance)); }); }
export async function markReviewed(vocabularyId: string) { return transaction([PERFORMANCE, REVISION], "readwrite", async (tx) => { const store = tx.objectStore(PERFORMANCE); const performance = await requestValue(store.get(vocabularyId)) as WordPerformance | undefined; if (!performance) return; const next = { ...performance, reviewedAt: new Date().toISOString(), nextReviewAt: new Date(Date.now() + 2 * 86_400_000).toISOString() }; store.put(next); tx.objectStore(REVISION).put({ vocabularyId, priority: Math.max(0, priorityFor(next) - 12), reason: "weak", scheduledAt: next.reviewedAt, nextReviewAt: next.nextReviewAt } satisfies RevisionItem); }); }
