// Phase-7 tools data: lightweight references only; canonical vocabulary remains in the words store.
import type { VocabularyWord } from "@/data/vocabulary";
import { getWordPage, initializeVocabularyDb, toggleWordFavorite } from "@/lib/vocabulary-db";

export type WordToolState = { vocabularyId: string; difficult: boolean; pinned: boolean; updatedAt: string };
export type PersonalNote = { vocabularyId: string; note: string; updatedAt: string };
export type CustomList = { listId: string; name: string; description?: string; createdAt: string; updatedAt: string };
export type WordOfDay = { date: string; vocabularyId: string; completed: boolean; createdAt: string };
const WORD_TOOLS = "word-tools"; const NOTES = "personal-notes"; const LISTS = "custom-lists"; const LIST_ITEMS = "custom-list-items"; const WORD_OF_DAY = "word-of-day"; const TOOL_HISTORY = "tool-history";
const get = <T,>(request: IDBRequest<T>) => new Promise<T>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("Local tool data could not be read.")); });
async function transaction<T>(stores: string | string[], mode: IDBTransactionMode, action: (tx: IDBTransaction) => Promise<T>) { const db = await initializeVocabularyDb(); try { return await action(db.transaction(stores, mode)); } finally { db.close(); } }
export const localDateKey = (value = new Date()) => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`;
export async function getWordToolState(vocabularyId: string) { return transaction(WORD_TOOLS, "readonly", async (tx) => (await get(tx.objectStore(WORD_TOOLS).get(vocabularyId)) as WordToolState | undefined) ?? { vocabularyId, difficult: false, pinned: false, updatedAt: "" }); }
export async function toggleWordTool(vocabularyId: string, key: "difficult" | "pinned") { return transaction(WORD_TOOLS, "readwrite", async (tx) => { const store = tx.objectStore(WORD_TOOLS); const current = (await get(store.get(vocabularyId)) as WordToolState | undefined) ?? { vocabularyId, difficult: false, pinned: false, updatedAt: "" }; const next = { ...current, [key]: !current[key], updatedAt: new Date().toISOString() }; store.put(next); return next; }); }
export async function getPersonalNote(vocabularyId: string) { return transaction(NOTES, "readonly", async (tx) => (await get(tx.objectStore(NOTES).get(vocabularyId)) as PersonalNote | undefined) ?? null); }
export async function savePersonalNote(vocabularyId: string, note: string) { return transaction(NOTES, "readwrite", async (tx) => { const store = tx.objectStore(NOTES); const trimmed = note.trim(); if (!trimmed) store.delete(vocabularyId); else store.put({ vocabularyId, note: trimmed, updatedAt: new Date().toISOString() } satisfies PersonalNote); }); }
export async function createCustomList(name: string, description?: string) { const clean = name.trim(); if (!clean) throw new Error("List name is required."); const list: CustomList = { listId: crypto.randomUUID?.() ?? `list-${Date.now()}`, name: clean, description: description?.trim() || undefined, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; await transaction(LISTS, "readwrite", async (tx) => { tx.objectStore(LISTS).put(list); }); return list; }
export async function getCustomLists() { return transaction(LISTS, "readonly", async (tx) => (await get(tx.objectStore(LISTS).getAll()) as CustomList[]).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))); }
export async function setListMembership(listId: string, vocabularyId: string, present: boolean) { return transaction(LIST_ITEMS, "readwrite", async (tx) => { const store = tx.objectStore(LIST_ITEMS); const listItemId = `${listId}:${vocabularyId}`; if (present) store.put({ listItemId, listId, vocabularyId, addedAt: new Date().toISOString() }); else store.delete(listItemId); }); }
export async function getMemberships(vocabularyId: string) { return transaction(LIST_ITEMS, "readonly", async (tx) => (await get(tx.objectStore(LIST_ITEMS).index("vocabularyId").getAll(vocabularyId)) as Array<{ listId: string; vocabularyId: string }>).map((item) => item.listId)); }
export async function getListItems(listId: string) { return transaction(LIST_ITEMS, "readonly", async (tx) => (await get(tx.objectStore(LIST_ITEMS).index("listId").getAll(listId)) as Array<{ vocabularyId: string }>).map((item) => item.vocabularyId)); }
export async function getWordOfDay() { const date = localDateKey(); return transaction([WORD_OF_DAY, "words", WORD_TOOLS], "readwrite", async (tx) => { const daily = tx.objectStore(WORD_OF_DAY); const stored = await get(daily.get(date)) as WordOfDay | undefined; const words = tx.objectStore("words"); if (stored) { const word = await get(words.get(stored.vocabularyId)) as VocabularyWord | undefined; if (word) return { word, state: stored }; }
  const all = await get(words.getAll()) as VocabularyWord[]; if (!all.length) return null; const tools = await get(tx.objectStore(WORD_TOOLS).getAll()) as WordToolState[]; const difficult = new Set(tools.filter((item) => item.difficult).map((item) => item.vocabularyId)); const offset = Number(date.replaceAll("-", "")) % all.length; const chosen = [...all.filter((item) => difficult.has(item.id)), ...all.filter((item) => !difficult.has(item.id))][offset % all.length] ?? all[offset]; const state: WordOfDay = { date, vocabularyId: chosen.id, completed: false, createdAt: new Date().toISOString() }; daily.put(state); return { word: chosen, state }; }); }
export async function markWordOfDayCompleted() { const date = localDateKey(); return transaction(WORD_OF_DAY, "readwrite", async (tx) => { const store = tx.objectStore(WORD_OF_DAY); const current = await get(store.get(date)) as WordOfDay | undefined; if (current) store.put({ ...current, completed: true }); }); }
export async function recordToolEvent(eventId: string, type: string, vocabularyId?: string) { return transaction(TOOL_HISTORY, "readwrite", async (tx) => { const store = tx.objectStore(TOOL_HISTORY); if (await get(store.get(eventId))) return false; store.put({ eventId, type, vocabularyId, createdAt: new Date().toISOString() }); return true; }); }
export async function getToolCollection(kind: "favorites" | "difficult" | "pinned" | "random", limit = 80) { const page = await getWordPage({ limit: Math.max(limit * 3, 240) }); if (kind === "favorites") return page.items.filter((word) => word.favorite).slice(0, limit); if (kind === "random") return [...page.items].sort(() => Math.random() - 0.5).slice(0, limit); const states = await transaction(WORD_TOOLS, "readonly", async (tx) => get(tx.objectStore(WORD_TOOLS).getAll()) as Promise<WordToolState[]>); const ids = new Set(states.filter((state) => state[kind]).map((state) => state.vocabularyId)); return page.items.filter((word) => ids.has(word.id)).slice(0, limit); }
export { toggleWordFavorite };
