// Scholar’s Ledger reminder: Phase‑2 exposes only trustworthy local vocabulary data, a compact parser, and no active learning tools.
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, BookMarked, Braces, ChevronRight, FileClock, Heart, LockKeyhole, Search, Settings2, Sparkles, Upload, Volume2 } from "lucide-react";
import { toast } from "sonner";
import { AppShell, type AppPage } from "@/components/AppShell";
import { MockTest } from "@/components/MockTest";
import { alphabet, type VocabularyWord, type WordRelation } from "@/data/vocabulary";
import { getDashboardStats, getExistingWordKeys, getWordPage, importVocabularyRecords, initializeVocabularyDb, removeSampleVocabulary, toggleWordFavorite, type LibraryStats } from "@/lib/vocabulary-db";
import { parseVocabularyText, type ParsedRecord, type ParserResult } from "@/lib/vocabulary-parser";
import { futureTools } from "@/lib/tool-registry";

type Page = AppPage;
type BankView = { input: string; query: string; letter: string; limit: number };
type ParserStage = "idle" | "parsing" | "checking" | "preview" | "saving" | "complete";
const PAGE_SIZE = 20;
const asset = (name: string) => `https://mocktest84-g8afqveb.manus.space/manus-storage/${name}`;
const relationText = (items: WordRelation[], limit = 4) => items.slice(0, limit).map((item) => item.word).join(" · ");
const number = new Intl.NumberFormat("en-US");

function EmptyIcon({ children }: { children: React.ReactNode }) { return <div className="empty-icon">{children}</div>; }

function Dashboard({ stats, onBank, onParser, onLetter }: { stats: LibraryStats | null; onBank: () => void; onParser: () => void; onLetter: (letter: string) => void }) {
  const hour = new Date().getHours(); const greeting = hour < 12 ? "Good morning." : hour < 18 ? "Good afternoon." : "Good evening.";
  if (!stats || stats.totalWords === 0) return <section className="page-section dashboard-phase2"><p className="kicker">VOCABULARY MASTER · PHASE‑2</p><h1>{greeting}</h1><p className="lead-copy">Your vocabulary library is empty. Start by adding vocabulary.</p><section className="empty-card"><EmptyIcon><Braces size={23}/></EmptyIcon><h2>Build your first collection.</h2><p>Paste structured vocabulary, review it, then import valid records into your local library.</p><button className="primary-btn" onClick={onParser}>Open Parser <ArrowRight size={17}/></button></section></section>;
  const letters = alphabet.filter((letter) => stats.letterCounts[letter]);
  return <section className="page-section dashboard-phase2"><div className="dashboard-heading"><div><p className="kicker">VOCABULARY MASTER · PHASE‑2</p><h1>{greeting}</h1><p>Build your vocabulary with a real local library.</p></div></div><section className="library-card"><p className="kicker">YOUR VOCABULARY</p><strong>{number.format(stats.totalWords)}</strong><span>Words in your library</span><div className="library-metrics"><span><b>{number.format(stats.withSynonyms)}</b> With synonyms</span><span><b>{number.format(stats.withAntonyms)}</b> With antonyms</span></div></section><section className="explore-card"><div><p className="kicker">EXPLORE VOCABULARY</p><h2>Find the right word.</h2><p>Browse the collection alphabetically or search across meanings and relations.</p></div><button className="primary-btn" onClick={onBank}>Open Vocabulary Bank <ArrowRight size={17}/></button></section><section className="dashboard-letter-section"><div><p className="kicker">A–Z QUICK ACCESS</p><h2>Jump to a letter.</h2></div><div className="dashboard-letter-grid">{letters.map((letter) => <button key={letter} onClick={() => onLetter(letter)}><strong>{letter}</strong><small>{number.format(stats.letterCounts[letter])}</small></button>)}</div></section><section className="quick-tools"><button onClick={onBank}><BookMarked size={18}/><span><strong>Vocabulary Bank</strong><small>Browse every stored word</small></span><ChevronRight size={17}/></button>{futureTools.parser.active && <button onClick={onParser}><Braces size={18}/><span><strong>Vocabulary Parser</strong><small>Paste, review and import</small></span><ChevronRight size={17}/></button>}</section></section>;
}

function BankLanding({ stats, onOpenCategory }: { stats: LibraryStats | null; onOpenCategory: (letter: string) => void }) {
  return <section className="page-section bank-landing"><div className="page-title"><div><p className="kicker">VOCABULARY BANK</p><h1>Explore by letter.</h1><p>Choose a category to browse your vocabulary.</p></div><span>{number.format(stats?.totalWords ?? 0)} stored</span></div><div className="category-grid">{alphabet.map((letter) => { const count = stats?.letterCounts[letter] ?? 0; return <button key={letter} className={count ? "category-box" : "category-box empty"} onClick={() => count && onOpenCategory(letter)} disabled={!count}><strong>{letter}</strong><small>{number.format(count)} {count === 1 ? "word" : "words"}</small></button>; })}</div></section>;
}

function RelationRows({ title, values }: { title: string; values: WordRelation[] }) { return <section className="large-card-section"><p className="kicker">{title.toUpperCase()}</p>{values.length ? <ol>{values.map((value, index) => <li key={`${value.word}-${index}`}><strong>{value.word}</strong><span>{value.meaningBn || "—"}</span></li>)}</ol> : <p className="detail-empty">No {title.toLowerCase()} added.</p>}</section>; }

function LargeWordCard({ word, onOpen, onSave }: { word: VocabularyWord; onOpen: () => void; onSave: () => void }) {
  return <article className="large-word-card"><header><button className="large-card-title" onClick={onOpen}><span><h2>{word.word}</h2><p>{word.meaningBn}</p></span><ChevronRight size={21}/></button><button className={word.favorite ? "large-save saved" : "large-save"} onClick={onSave} aria-label={`Save ${word.word}`}><Heart size={19} fill={word.favorite ? "currentColor" : "none"}/></button></header><RelationRows title="Synonyms" values={word.synonyms}/><RelationRows title="Antonyms" values={word.antonyms}/>{word.tip && <section className="large-tip"><Sparkles size={18}/><div><p className="kicker">TIPS & EXPLANATION</p><p>{word.tip}</p></div></section>}</article>;
}

function CategoryPage({ ready, view, onChange, refreshKey, onOpen, onSave, onBack, restoreTop, onRestored }: { ready: boolean; view: BankView; onChange: (next: BankView) => void; refreshKey: number; onOpen: (word: VocabularyWord) => void; onSave: (id: string) => void; onBack: () => void; restoreTop: number | null; onRestored: () => void }) {
  const [items, setItems] = useState<VocabularyWord[]>([]); const [hasMore, setHasMore] = useState(false); const [loading, setLoading] = useState(true); const [stats, setStats] = useState<LibraryStats | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => onChange({ ...view, query: view.input.trim(), limit: PAGE_SIZE }), 220); return () => window.clearTimeout(timer); }, [view.input]);
  useEffect(() => { if (!ready) return; getDashboardStats().then(setStats).catch(() => toast.error("The vocabulary index could not be loaded.")); }, [ready, refreshKey]);
  useEffect(() => { if (!ready) return; let active = true; setLoading(true); getWordPage({ letter: view.letter, query: view.query, limit: view.limit }).then((page) => { if (active) { setItems(page.items); setHasMore(page.hasMore); } }).catch(() => { if (active) toast.error("The vocabulary list could not be loaded."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [ready, view.letter, view.query, view.limit, refreshKey]);
  useEffect(() => { if (restoreTop === null || loading) return; const frame = window.requestAnimationFrame(() => { window.scrollTo({ top: restoreTop, behavior: "auto" }); onRestored(); }); return () => window.cancelAnimationFrame(frame); }, [restoreTop, loading, items.length]);
  const count = stats?.letterCounts[view.letter] ?? 0; const setInput = (input: string) => onChange({ ...view, input, limit: PAGE_SIZE }); const clearSearch = () => onChange({ ...view, input: "", query: "", limit: PAGE_SIZE });
  return <section className="page-section category-page"><button className="back-btn" onClick={onBack}><ArrowLeft size={17}/> Vocabulary Bank</button><div className="category-heading"><div><p className="kicker">CATEGORY</p><h1>{view.letter} Vocabulary</h1><span>{number.format(count)} {count === 1 ? "word" : "words"}</span></div></div><label className="search-field"><Search size={19}/><input value={view.input} onChange={(event) => setInput(event.target.value)} placeholder={`Search ${view.letter} vocabulary…`} aria-label={`Search ${view.letter} vocabulary`}/></label><div className="category-result" aria-live="polite"><p className="kicker">{view.input ? "SEARCH RESULTS" : `${view.letter} VOCABULARY`}</p><span>{loading ? "Loading…" : items.length ? `${number.format(items.length)}${hasMore ? "+" : ""} shown` : "No vocabulary found."}</span>{view.input && <button onClick={clearSearch}>Clear</button>}</div>{items.length ? <><div className="large-card-list">{items.map((word) => <LargeWordCard key={word.id} word={word} onOpen={() => onOpen(word)} onSave={() => onSave(word.id)}/>)}</div>{hasMore && <button className="load-more" onClick={() => onChange({ ...view, limit: view.limit + PAGE_SIZE })}>Load 20 more words</button>}</> : !loading && <div className="empty-card"><Search size={22}/><h2>{count ? "No vocabulary found." : "No vocabulary yet."}</h2><p>{count ? "Try another word or meaning." : "This category is currently empty."}</p></div>}</section>;
}

function RelationSection({ title, values }: { title: string; values: WordRelation[] }) { return <section className="detail-section"><p className="kicker">{title.toUpperCase()}</p>{values.length ? <div>{values.map((value, index) => <span key={`${value.word}-${index}`}><b>{value.word}</b>{value.meaningBn && <small>{value.meaningBn}</small>}</span>)}</div> : <p className="detail-empty">No {title.toLowerCase()} added.</p>}</section>; }
function Detail({ word, onSave, onBack }: { word: VocabularyWord; onSave: () => void; onBack: () => void }) { return <section className="page-section"><button className="back-btn" onClick={onBack}><ArrowLeft size={17}/> Back to Bank</button><section className="word-hero"><div><p className="kicker">{word.firstLetter} · {word.category.toUpperCase()}</p><h1>{word.word}</h1><p>{word.meaningBn}</p></div><img src={asset("vocabulary-master-word-detail_d468e227.png")} alt="Academic paper detail"/></section><div className="ledger-rule"/><RelationSection title="Synonyms" values={word.synonyms}/><RelationSection title="Antonyms" values={word.antonyms}/>{word.tip && <section className="tip-card"><Sparkles size={18}/><div><p className="kicker">TIPS & EXPLANATION</p><strong>{word.tip}</strong></div></section>}<div className="detail-actions"><button className={word.favorite ? "secondary-btn saved" : "secondary-btn"} onClick={onSave}><Heart size={17} fill={word.favorite ? "currentColor" : "none"}/>{word.favorite ? "Saved to favorites" : "Save word"}</button><button className="secondary-btn" onClick={() => toast.info("Practice is locked in Phase‑2.")}><LockKeyhole size={16}/> Practice locked</button><button className="icon-btn" onClick={() => toast.info("Audio will be available in a future phase.")} aria-label="Audio is locked"><Volume2 size={18}/></button></div></section>; }

function Parser({ onImported, onBank }: { onImported: () => void; onBank: () => void }) {
  const [text, setText] = useState(""); const [stage, setStage] = useState<ParserStage>("idle"); const [result, setResult] = useState<ParserResult | null>(null); const [progress, setProgress] = useState({ completed: 0, total: 0 });
  const parse = async () => { if (!text.trim()) return toast.error("Paste vocabulary before parsing."); setStage("parsing"); await new Promise((resolve) => window.setTimeout(resolve, 0)); const parsed = parseVocabularyText(text); setStage("checking"); try { const existing = await getExistingWordKeys(parsed.records.map((record) => record.wordKey)); const records = parsed.records.map((record) => existing.has(record.wordKey) ? { ...record, duplicate: "existing" as const } : record); setResult({ ...parsed, records }); setStage("preview"); } catch { setStage("idle"); toast.error("Duplicate checking could not be completed."); } };
  const validRecords = result?.records.filter((record) => !record.duplicate) ?? []; const existingDuplicates = result?.records.filter((record) => record.duplicate === "existing").length ?? 0; const batchDuplicates = result?.records.filter((record) => record.duplicate === "batch").length ?? 0;
  const importRecords = async () => { if (!validRecords.length) return toast.error("There are no valid new records to import."); setStage("saving"); try { await importVocabularyRecords(validRecords, (next) => setProgress(next)); setStage("complete"); onImported(); toast.success(`${validRecords.length} vocabulary records imported locally.`); } catch { setStage("preview"); toast.error("Import failed. No partial import was reported as complete."); } };
  return <section className="page-section parser-page"><div className="page-title"><div><p className="kicker">LOCAL DATA MANAGEMENT</p><h1>Vocabulary Parser</h1></div><span>Phase‑2 active</span></div><p className="lead-copy">Paste vocabulary, review the preserved result, then import only valid new records.</p><label className="parser-input"><span>Paste vocabulary</span><textarea value={text} onChange={(event) => { setText(event.target.value); if (stage !== "idle") { setStage("idle"); setResult(null); } }} placeholder={'Conjecture : অনুমান করা\n* Synonyms:\n  * Hypothesis : প্রকল্প / অনুমিতি\n* Antonyms:\n  * Fact : সত্য / তথ্য\n* Tips & Explanation: ...'} /></label><button className="primary-btn" onClick={parse} disabled={stage === "parsing" || stage === "checking" || stage === "saving"}>{stage === "parsing" ? "Parsing…" : stage === "checking" ? "Checking duplicates…" : "Parse vocabulary"} <Braces size={17}/></button>{result && <section className="parser-preview"><div className="parser-summary"><div><small>Total</small><b>{result.records.length}</b></div><div><small>Valid</small><b>{validRecords.length}</b></div><div><small>Duplicates</small><b>{existingDuplicates + batchDuplicates}</b></div><div><small>Warnings</small><b>{result.issues.filter((issue) => issue.severity === "warning").length}</b></div><div><small>Errors</small><b>{result.issues.filter((issue) => issue.severity === "error").length}</b></div></div>{result.issues.length > 0 && <div className="parser-issues">{result.issues.slice(0, 8).map((issue, index) => <p key={`${issue.line}-${index}`} className={issue.severity}><b>Line {issue.line}</b> {issue.message}</p>)}</div>}<div className="preview-list">{result.records.slice(0, 30).map((record) => <article key={record.id}><div><strong>{record.word}</strong><span>{record.meaningBn}</span><small>{record.synonyms.length} synonyms · {record.antonyms.length} antonyms</small></div>{record.duplicate && <b className="duplicate-badge">{record.duplicate === "existing" ? "Already stored" : "Repeated in batch"}</b>}</article>)}</div>{result.records.length > 30 && <p className="note">Showing the first 30 parsed records for review.</p>}<div className="parser-actions"><button className="secondary-btn" onClick={() => { setResult(null); setStage("idle"); }}>Edit input</button><button className="primary-btn" onClick={importRecords} disabled={stage === "saving" || stage === "complete" || !validRecords.length}>{stage === "saving" ? `Saving ${progress.completed}/${progress.total}…` : stage === "complete" ? "Imported" : `Import ${validRecords.length} valid records`} <Upload size={17}/></button></div>{stage === "complete" && <button className="bank-link" onClick={onBank}>Open updated Vocabulary Bank <ArrowRight size={17}/></button>}</section>}</section>;
}

function LockedPractice() { const labels = (["match", "mock", "flash", "revision"] as const).map((key) => futureTools[key].label).join(", "); return <section className="page-section locked-page"><p className="kicker"><LockKeyhole size={14}/> PHASE‑2 · LOCKED</p><h1>Practice will open later.</h1><p>Vocabulary Master-এর learning tools এখনো সক্রিয় নয়। এখন Bank তৈরি করুন, শব্দ খুঁজুন এবং local vocabulary foundation প্রস্তুত রাখুন।</p><div><span><LockKeyhole size={15}/>{labels}</span><small>Only Parser and vocabulary data management are active in Phase‑2.</small></div></section>; }
function PracticeHub({ onMock }: { onMock: () => void }) { return <section className="page-section practice-hub"><p className="kicker">PRACTICE & EXAM</p><h1>Choose your mode.</h1><p className="lead-copy">Practice lessons remain locked. Mock Test evaluates your imported vocabulary under exam conditions.</p><section><LockKeyhole size={20}/><div><strong>Practice</strong><span>Learning modes will open in a later phase.</span></div><small>Locked</small></section><section className="mock-entry"><FileClock size={20}/><div><strong>Mock Test</strong><span>Timer, scoring, result and local exam history.</span></div><button className="primary-btn" onClick={onMock}>Open Mock Test <ArrowRight size={16}/></button></section></section>; }
function History({ onBank }: { onBank: () => void }) { return <section className="page-section center-empty"><EmptyIcon><BookMarked size={23}/></EmptyIcon><p className="kicker">HISTORY</p><h1>No activity yet.</h1><p>Vocabulary import and saved words stay local. Learning history will appear in a future phase.</p><button className="secondary-btn" onClick={onBank}>Open Vocabulary Bank <ArrowRight size={16}/></button></section>; }
function Profile({ onSettings }: { onSettings: () => void }) { return <section className="page-section"><p className="kicker">PROFILE</p><h1>Your vocabulary journey.</h1><section className="profile-card"><img src={asset("vocabulary-master-mark_cabe734c.png")} alt="Vocabulary Master mark"/><div><strong>Vocabulary Master</strong><span>Phase‑2 local data foundation</span></div></section><div className="settings-list"><button onClick={onSettings}><Settings2 size={19}/><span>Settings</span><ChevronRight size={18}/></button><button onClick={() => toast.info("Saved words are kept locally on this device.")}><Heart size={19}/><span>Favorites</span><ChevronRight size={18}/></button></div></section>; }
function Settings() { return <section className="page-section"><p className="kicker">SETTINGS</p><h1>Keep your desk calm.</h1><div className="settings-list"><div><span>◐</span><p><strong>Appearance</strong><small>Premium Light · active</small></p><b>Active</b></div><div><span>⌁</span><p><strong>Motion</strong><small>Respects device reduced-motion preference</small></p></div><div><span>▣</span><p><strong>Data foundation</strong><small>Local IndexedDB · version 3</small></p></div><div><Braces size={18}/><p><strong>Vocabulary Parser</strong><small>Local import and duplicate checks · active</small></p></div></div><p className="note">Only Phase‑2 data tools are shown as active.</p></section>; }

export default function Home() {
  const [page, setPage] = useState<Page>("home"); const [selected, setSelected] = useState<VocabularyWord | null>(null); const [ready, setReady] = useState(false); const [dataRevision, setDataRevision] = useState(0); const [stats, setStats] = useState<LibraryStats | null>(null); const [restoreTop, setRestoreTop] = useState<number | null>(null); const [bankView, setBankView] = useState<BankView>({ input: "", query: "", letter: "", limit: PAGE_SIZE }); const bankScrollTop = useRef(0); const [welcome, setWelcome] = useState(() => localStorage.getItem("vm-onboarding-seen") !== "1");
  const refreshData = async () => { const next = await getDashboardStats(); setStats(next); setDataRevision((value) => value + 1); };
  useEffect(() => { let active = true; initializeVocabularyDb().then(async () => { await removeSampleVocabulary(); const nextStats = await getDashboardStats(); if (active) { setStats(nextStats); setReady(true); } }).catch(() => toast.error("Something went wrong while preparing local data.")); return () => { active = false; }; }, []);
  const navigate = (next: Page) => { setSelected(null); setPage(next); window.scrollTo({ top: 0, behavior: "auto" }); }; const openBank = () => { setBankView({ input: "", query: "", letter: "", limit: PAGE_SIZE }); navigate("bank"); }; const openLetter = (letter: string) => { setBankView({ input: "", query: "", letter, limit: PAGE_SIZE }); navigate("category"); }; const openWord = (word: VocabularyWord) => { bankScrollTop.current = window.scrollY; setSelected(word); window.scrollTo({ top: 0, behavior: "auto" }); }; const returnFromDetail = () => { setSelected(null); setRestoreTop(bankScrollTop.current); }; const toggleFavorite = async (id: string) => { try { const favorite = await toggleWordFavorite(id); setSelected((current) => current?.id === id ? { ...current, favorite } : current); setDataRevision((value) => value + 1); toast.success(favorite ? "Word saved locally." : "Word removed from favorites."); } catch { toast.error("This word could not be saved."); } };
  const pageView = page === "home" ? <Dashboard stats={stats} onBank={openBank} onParser={() => navigate("parser")} onLetter={openLetter}/> : page === "bank" ? <BankLanding stats={stats} onOpenCategory={openLetter}/> : page === "category" && selected ? <Detail word={selected} onSave={() => toggleFavorite(selected.id)} onBack={returnFromDetail}/> : page === "category" ? <CategoryPage ready={ready} view={bankView} onChange={setBankView} refreshKey={dataRevision} onOpen={openWord} onSave={toggleFavorite} onBack={openBank} restoreTop={restoreTop} onRestored={() => setRestoreTop(null)}/> : page === "parser" ? <Parser onImported={refreshData} onBank={openBank}/> : page === "practice" ? <PracticeHub onMock={() => navigate("mock")}/> : page === "mock" ? <MockTest onBack={() => navigate("home")}/> : page === "history" ? <MockTest onBack={() => navigate("home")} initialView="history"/> : page === "profile" ? <Profile onSettings={() => navigate("settings")}/> : <Settings/>;
  const closeWelcome = (goBank = false) => { localStorage.setItem("vm-onboarding-seen", "1"); setWelcome(false); if (goBank) openBank(); };
  return <><AppShell page={page} onNavigate={navigate} onProfile={() => navigate("profile")}>{pageView}{!ready && <p className="db-status">Preparing local vocabulary desk…</p>}</AppShell>{welcome && <div className="welcome-layer"><section className="welcome-sheet"><img src={asset("vocabulary-master-mark_cabe734c.png")} alt="Vocabulary Master"/><p className="kicker">VOCABULARY MASTER</p><h1>Build a real<br/>vocabulary library.</h1><p>Paste, review and save vocabulary locally. Learning tools remain locked for now.</p><button className="primary-btn" onClick={() => closeWelcome(true)}>Explore Vocabulary Bank <ArrowRight size={17}/></button><button className="skip" onClick={() => closeWelcome()}>Skip for now</button></section></div>}</>;
}
