// Phase-4 Mock Test: a focused local exam flow that never reveals correctness before an exam is submitted.
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, ChevronRight, Clock3, FileClock, Flag, History, LockKeyhole, Play, RotateCcw, Sparkles, Timer, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { alphabet } from "@/data/vocabulary";
import { createQuestions, formatTime, scoreExam, type ExamHistoryRecord, type ExamSession, type ExamSettings } from "@/lib/exam-engine";
import { discardActiveExam, finalizeExam, getActiveExam, getExamCandidates, getExamHistory, saveActiveExam } from "@/lib/exam-db";

type MockView = "hub" | "setup" | "confirm" | "exam" | "result" | "review" | "history";
const initialSettings: ExamSettings = { source: "all", questionCount: 20, timeMinutes: 10, difficulty: "all", negativeMarking: 0 };
const questionCounts = [10, 20, 30, 50, 100] as const; const timeLimits = [5, 10, 20, 30, 60] as const;

function ResultSummary({ record }: { record: ExamHistoryRecord }) { return <section className="exam-result-card"><p className="kicker">{record.status === "expired" ? "TIME'S UP" : "TEST COMPLETE"}</p><strong>{record.finalScore} <small>/ {record.totalQuestions}</small></strong><span>Final score</span><div><p><b>{record.accuracy}%</b><small>Accuracy</small></p><p><b>{record.correct}</b><small>Correct</small></p><p><b>{record.wrong}</b><small>Wrong</small></p><p><b>{record.skipped}</b><small>Skipped</small></p></div></section>; }

export function MockTest({ onBack, initialView = "hub" }: { onBack: () => void; initialView?: "hub" | "history" }) {
  const [view, setView] = useState<MockView>(initialView); const [settings, setSettings] = useState<ExamSettings>(initialSettings); const [draft, setDraft] = useState<ExamSession | null>(null); const [session, setSession] = useState<ExamSession | null>(null); const [result, setResult] = useState<ExamHistoryRecord | null>(null); const [history, setHistory] = useState<ExamHistoryRecord[]>([]); const [now, setNow] = useState(Date.now()); const [reviewFilter, setReviewFilter] = useState<"all" | "correct" | "wrong" | "skipped">("all"); const [submitPrompt, setSubmitPrompt] = useState(false);
  const refreshHistory = async () => setHistory(await getExamHistory());
  useEffect(() => { void refreshHistory(); void getActiveExam().then((active) => { if (active && active.status === "active") setSession(active); }); }, []);
  useEffect(() => { setView(initialView); }, [initialView]);
  useEffect(() => { if (!session || view !== "exam") return; const tick = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(tick); }, [session, view]);
  const remaining = session ? Math.max(0, Math.ceil((Date.parse(session.expiresAt) - now) / 1000)) : 0;
  useEffect(() => { if (session && view === "exam" && remaining <= 0) void complete("expired"); }, [remaining]);
  const answered = session ? Object.keys(session.answers).length : 0;
  const currentQuestion = session?.questions[session.currentQuestion];
  const prepare = async () => { const candidates = await getExamCandidates(Math.max(120, settings.questionCount * 6), settings.source); const questions = createQuestions(candidates, settings); if (!questions.length) { toast.error("No valid vocabulary is available for a Mock Test yet."); return; } const effectiveSettings = { ...settings, questionCount: questions.length as ExamSettings["questionCount"] }; const startedAt = new Date().toISOString(); setDraft({ examId: crypto.randomUUID?.() ?? `mock-${Date.now()}`, mode: "mock", startedAt, expiresAt: new Date(Date.now() + effectiveSettings.timeMinutes * 60_000).toISOString(), settings: effectiveSettings, currentQuestion: 0, questions, answers: {}, status: "active" }); setView("confirm"); };
  const start = async () => { if (!draft) return; await saveActiveExam(draft); setSession(draft); setNow(Date.now()); setView("exam"); };
  const choose = (answer: string) => { if (!session || !currentQuestion || session.status !== "active") return; const next = { ...session, answers: { ...session.answers, [currentQuestion.id]: answer } }; setSession(next); void saveActiveExam(next); };
  const move = (index: number) => { if (!session) return; const next = { ...session, currentQuestion: Math.max(0, Math.min(index, session.questions.length - 1)) }; setSession(next); void saveActiveExam(next); window.scrollTo({ top: 0, behavior: "auto" }); };
  const complete = async (status: "submitted" | "expired") => { if (!session || session.status !== "active") return; const locked = { ...session, status }; setSession(locked); const record = scoreExam(locked, status); await finalizeExam(record); setResult(record); await refreshHistory(); setSubmitPrompt(false); setView("result"); };
  const discard = async () => { if (!session) return; await discardActiveExam(session.examId); setSession(null); setView("hub"); };
  const activeSession = session && session.status === "active" ? session : null;
  const reviewItems = useMemo(() => result?.questionResults.filter((item) => reviewFilter === "all" || item.status === reviewFilter) ?? [], [result, reviewFilter]);
  if (view === "hub") return <section className="page-section mock-hub"><button className="back-btn" onClick={onBack}><ArrowLeft size={17}/> Back</button><p className="kicker">MOCK TEST · PHASE‑4</p><h1>Test yourself.</h1><p className="lead-copy">A focused vocabulary exam with no answer feedback until submission.</p>{activeSession && <section className="resume-exam"><FileClock size={20}/><div><strong>Unfinished Mock Test</strong><span>{activeSession.questions.length} questions · {formatTime(Math.max(0, Math.ceil((Date.parse(activeSession.expiresAt) - Date.now()) / 1000)))} remaining</span></div><button onClick={() => { setNow(Date.now()); setView("exam"); }}>Resume</button></section>}<div className="mock-hub-actions"><button className="primary-btn" onClick={() => setView("setup")}><Play size={17}/> Start New Test</button><button className="secondary-btn" onClick={() => { void refreshHistory(); setView("history"); }}><History size={17}/> Exam History</button></div></section>;
  if (view === "setup") return <section className="page-section exam-setup"><button className="back-btn" onClick={() => setView("hub")}><ArrowLeft size={17}/> Mock Test</button><p className="kicker">EXAM SETUP</p><h1>Set your conditions.</h1><div className="setup-list"><label>Vocabulary Source<select value={settings.source} onChange={(event) => setSettings({ ...settings, source: event.target.value })}><option value="all">All Vocabulary</option>{alphabet.map((letter) => <option key={letter} value={letter}>{letter} Vocabulary</option>)}</select></label><label>Question Type<select disabled value="mixed"><option>Mixed</option></select></label><label>Questions<select value={settings.questionCount} onChange={(event) => setSettings({ ...settings, questionCount: Number(event.target.value) as ExamSettings["questionCount"] })}>{questionCounts.map((count) => <option key={count} value={count}>{count}</option>)}</select></label><label>Time<select value={settings.timeMinutes} onChange={(event) => setSettings({ ...settings, timeMinutes: Number(event.target.value) as ExamSettings["timeMinutes"] })}>{timeLimits.map((minutes) => <option key={minutes} value={minutes}>{minutes} min</option>)}</select></label><label>Difficulty<select value={settings.difficulty} onChange={(event) => setSettings({ ...settings, difficulty: event.target.value as ExamSettings["difficulty"] })}><option value="all">All levels</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="advanced">Advanced</option></select></label><label>Negative Marking<select value={settings.negativeMarking} onChange={(event) => setSettings({ ...settings, negativeMarking: Number(event.target.value) as ExamSettings["negativeMarking"] })}><option value={0}>Off</option><option value={0.25}>−0.25</option><option value={0.5}>−0.50</option></select></label></div><button className="primary-btn setup-start" onClick={() => void prepare()}>Prepare Test <ArrowRight size={17}/></button><p className="note">Questions are created only from valid local vocabulary. If fewer questions are available, the test is limited safely.</p></section>;
  if (view === "confirm" && draft) return <section className="page-section exam-confirm"><button className="back-btn" onClick={() => setView("setup")}><ArrowLeft size={17}/> Edit setup</button><p className="kicker">READY TO BEGIN</p><h1>Mock Test</h1><div className="exam-rule-card"><p><b>{draft.questions.length}</b> Questions</p><p><b>{draft.settings.timeMinutes}</b> Minutes</p><p><b>{draft.settings.negativeMarking ? `−${draft.settings.negativeMarking}` : "Off"}</b> Negative marking</p></div><div className="exam-rules"><p><LockKeyhole size={16}/> No answer feedback during the test.</p><p><Timer size={16}/> The timer submits automatically at zero.</p><p><Flag size={16}/> Answers remain saved if the page refreshes.</p></div><button className="primary-btn" onClick={() => void start()}>Start Exam <Play size={17}/></button></section>;
  if (view === "exam" && session && currentQuestion) return <section className="exam-screen"><header className="exam-top"><button onClick={() => { if (window.confirm("Exit & discard this unfinished Mock Test?")) void discard(); }}><ArrowLeft size={17}/> Exit</button><strong className={remaining <= 60 ? "critical" : remaining <= 180 ? "warning" : ""}><Clock3 size={17}/>{formatTime(remaining)}</strong></header><main className="exam-body"><p className="kicker">QUESTION {session.currentQuestion + 1} / {session.questions.length}</p><div className="exam-progress"><i style={{ width: `${((session.currentQuestion + 1) / session.questions.length) * 100}%` }}/></div><h1>{currentQuestion.prompt}</h1><div className="exam-options">{currentQuestion.options.map((option, index) => <button key={option} className={session.answers[currentQuestion.id] === option ? "selected" : ""} onClick={() => choose(option)}><span>{String.fromCharCode(65 + index)}</span>{option}</button>)}</div><div className="question-nav">{session.questions.map((question, index) => <button key={question.id} className={`${index === session.currentQuestion ? "current" : ""} ${session.answers[question.id] ? "answered" : ""}`} onClick={() => move(index)}>{index + 1}</button>)}</div></main><footer className="exam-bottom"><button className="secondary-btn" disabled={session.currentQuestion === 0} onClick={() => move(session.currentQuestion - 1)}>Previous</button><button className="secondary-btn" disabled={session.currentQuestion === session.questions.length - 1} onClick={() => move(session.currentQuestion + 1)}>Next</button><button className="submit-exam" onClick={() => setSubmitPrompt(true)}>Submit Test</button></footer>{submitPrompt && <div className="exam-modal"><section><TriangleAlert size={22}/><h2>Submit your test?</h2><p>Answered: {answered} / {session.questions.length}</p><div><button className="secondary-btn" onClick={() => setSubmitPrompt(false)}>Cancel</button><button className="primary-btn" onClick={() => void complete("submitted")}>Submit Test</button></div></section></div>}</section>;
  if (view === "result" && result) return <section className="page-section exam-result"><ResultSummary record={result}/><div className="result-details"><span>Time used <b>{formatTime(result.durationSeconds)}</b></span><span>Negative marks <b>{result.negativeMarks}</b></span><span>Positive marks <b>{result.positiveMarks}</b></span></div><div className="mock-hub-actions"><button className="primary-btn" onClick={() => setView("review")}>Review Answers <ArrowRight size={17}/></button><button className="secondary-btn" onClick={() => { setSettings(initialSettings); setView("setup"); }}><RotateCcw size={17}/> New Mock Test</button><button className="secondary-btn" onClick={onBack}>Back to Dashboard</button></div></section>;
  if (view === "review" && result) return <section className="page-section exam-review"><button className="back-btn" onClick={() => setView("result")}><ArrowLeft size={17}/> Result</button><p className="kicker">EXAM REVIEW</p><h1>Review answers.</h1><div className="review-filters">{(["all", "wrong", "correct", "skipped"] as const).map((filter) => <button key={filter} className={reviewFilter === filter ? "active" : ""} onClick={() => setReviewFilter(filter)}>{filter}</button>)}</div><div className="review-list">{reviewItems.map((question, index) => <article key={question.id} className={question.status}><p className="kicker">QUESTION {index + 1} · {question.status}</p><h2>{question.prompt}</h2><p>Your answer <b>{question.selectedOption ?? "Skipped"}</b></p><p>Correct answer <b>{question.correctOption}</b></p><p>Bengali meaning <b>{question.meaningBn}</b></p>{question.tip && <div className="review-tip"><Sparkles size={16}/>{question.tip}</div>}</article>)}</div></section>;
  return <section className="page-section exam-history"><button className="back-btn" onClick={onBack}><ArrowLeft size={17}/> Back</button><p className="kicker">EXAM HISTORY</p><h1>Past Mock Tests.</h1>{history.length ? <div className="history-list">{history.map((record) => <button key={record.examId} onClick={() => { setResult(record); setView("result"); }}><span>{new Date(record.completedAt).toLocaleDateString()}</span><strong>{record.finalScore} / {record.totalQuestions}</strong><small>{record.accuracy}% accuracy · {formatTime(record.durationSeconds)}</small><ChevronRight size={17}/></button>)}</div> : <div className="empty-card"><History size={22}/><h2>No mock tests yet.</h2><p>Complete your first test to build your exam history.</p><button className="primary-btn" onClick={() => setView("setup")}>Start Mock Test</button></div>}</section>;
}
