// Phase-5 learning surfaces: actionable Mistake Bank and adaptive revision queue, driven only by stored performance evidence.
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpenCheck, Check, CircleAlert, Clock3, Gauge, Search, Sparkles } from "lucide-react";
import { getMistakes, getPerformanceSummary, getRevisionItems, markReviewed } from "@/lib/performance-db";
import type { WordPerformance } from "@/lib/performance-engine";
import type { VocabularyWord } from "@/data/vocabulary";

type MistakeRow = { performance: WordPerformance; word: VocabularyWord };
const stateLabel = (value: WordPerformance) => value.currentState === "mastered" ? "Mastered" : value.currentState === "strong" ? "Strong" : value.currentState === "reviewing" ? "Reviewing" : value.currentState === "learning" ? "Learning" : value.currentState === "weak" ? "Weak" : "New";
export function MistakeBank({ onBack }: { onBack: () => void }) { const [rows, setRows] = useState<MistakeRow[]>([]); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<"all" | "recent" | "wrong" | "accuracy">("all"); const load = () => void getMistakes().then(setRows); useEffect(load, []); const shown = useMemo(() => rows.filter((row) => `${row.word.word} ${row.word.meaningBn}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b) => filter === "wrong" ? b.performance.wrong-a.performance.wrong : filter === "accuracy" ? a.performance.accuracy-b.performance.accuracy : filter === "recent" ? Date.parse(b.performance.lastWrongAt ?? "0")-Date.parse(a.performance.lastWrongAt ?? "0") : 0), [rows, query, filter]); return <section className="page-section phase5-page"><button className="back-btn" onClick={onBack}><ArrowLeft size={17}/> Back</button><p className="kicker">MISTAKE BANK</p><h1>Review what missed.</h1><p className="lead-copy">Each card references one original vocabulary word; repeated wrong answers never create duplicates.</p>{rows.length ? <><label className="search-field"><Search size={18}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search word or Bengali meaning"/></label><div className="review-filters">{(["all","recent","wrong","accuracy"] as const).map((item)=><button className={filter===item?"active":""} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</div><div className="mistake-list">{shown.map(({word,performance})=><article key={word.id}><div><p className="kicker">{stateLabel(performance)}</p><h2>{word.word}</h2><p>{word.meaningBn}</p></div><div className="mistake-metrics"><span><b>{performance.wrong}</b> mistakes</span><span><b>{performance.accuracy}%</b> accuracy</span></div><small>Last mistake: {performance.lastWrongAt ? new Date(performance.lastWrongAt).toLocaleDateString() : "—"}</small></article>)}</div></> : <div className="empty-card"><BookOpenCheck size={23}/><h2>Excellent!</h2><p>You currently have no vocabulary mistakes to review.</p></div>}</section>; }
export function SmartRevision({ onBack }: { onBack: () => void }) { const [rows, setRows] = useState<Array<{item:{reason:string;priority:number};word:VocabularyWord}>>([]); const [started,setStarted]=useState(false); const [index,setIndex]=useState(0); const load=()=>void getRevisionItems().then(setRows); useEffect(load,[]); const current=rows[index]; const counts=useMemo(()=>({due:rows.filter(r=>r.item.reason==="due").length, weak:rows.filter(r=>r.item.reason==="weak").length, recent:rows.filter(r=>r.item.reason==="recently-wrong").length}),[rows]); const mark=async()=>{if(!current)return; await markReviewed(current.word.id); if(index+1<rows.length)setIndex(index+1); else {setStarted(false);setIndex(0);load();}}; if(started && current)return <section className="page-section phase5-page revision-session"><button className="back-btn" onClick={()=>setStarted(false)}><ArrowLeft size={17}/> Revision overview</button><p className="kicker">SMART REVISION · {index+1}/{rows.length}</p><article className="revision-word"><h1>{current.word.word}</h1><p>{current.word.meaningBn}</p><section><p className="kicker">SYNONYMS</p><p>{current.word.synonyms.map(x=>x.word).join(" · ") || "No synonyms added."}</p></section><section><p className="kicker">ANTONYMS</p><p>{current.word.antonyms.map(x=>x.word).join(" · ") || "No antonyms added."}</p></section>{current.word.tip&&<section className="revision-tip"><Sparkles size={17}/>{current.word.tip}</section>}</article><button className="primary-btn" onClick={()=>void mark()}>Mark reviewed <Check size={17}/></button></section>; return <section className="page-section phase5-page"><button className="back-btn" onClick={onBack}><ArrowLeft size={17}/> Back</button><p className="kicker">SMART REVISION</p><h1>Focus what needs attention.</h1>{rows.length ? <><p className="lead-copy"><b>{rows.length}</b> words need your attention. Priority adapts to mistakes, recency and due review.</p><div className="revision-counts"><span><b>{counts.due}</b> Due</span><span><b>{counts.weak}</b> Weak</span><span><b>{counts.recent}</b> Recently missed</span></div><button className="primary-btn" onClick={()=>setStarted(true)}>Start Smart Revision <ArrowRight size={17}/></button></> : <div className="empty-card"><Clock3 size={23}/><h2>You’re all caught up.</h2><p>No vocabulary requires revision right now.</p></div>}</section>; }
export function MasteryPanel({ onBack }: { onBack: () => void }) { const [summary,setSummary]=useState({overall:0,tracked:0,weak:0,strong:0,mastered:0}); useEffect(()=>void getPerformanceSummary().then(setSummary),[]); return <section className="page-section phase5-page"><button className="back-btn" onClick={onBack}><ArrowLeft size={17}/> Back</button><p className="kicker">VOCABULARY MASTERY</p><h1>Evidence-based progress.</h1>{summary.tracked ? <><section className="mastery-overview"><Gauge size={23}/><div><strong>{summary.overall}%</strong><span>Overall mastery</span></div></section><div className="mastery-grid"><span><b>{summary.mastered}</b> Mastered</span><span><b>{summary.strong}</b> Strong</span><span><b>{summary.weak}</b> Weak</span><span><b>{summary.tracked}</b> Tracked</span></div><p className="note">Mastery requires repeated evidence. One correct answer cannot make a word mastered.</p></> : <div className="empty-card"><Gauge size={23}/><h2>Mastery will grow from evidence.</h2><p>Complete Mock Tests to start building mastery data.</p></div>}</section>; }
